# Generated by Django 5.0.7 on 2024-08-01 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='id',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='id',
            new_name='uuid',
        ),
    ]
