# Generated by Django 5.0.7 on 2024-08-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_id_collection_uuid_rename_id_movie_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.CharField(default='', max_length=255),
        ),
    ]
